### ISSUE TITLE
Crazy RAM usage

### ISSUE THREAD

**Issue by Demonslay335** [stong/hxd-plugin#1]
I am getting crazy RAM usage with HxD when opening files and having this plugin enabled; it will actually freeze the application temporarily with a "Not responding". It seems to happen every time with a high-entropy file (encrypted/compressed), otherwise is kind of hit or miss on "regular" files.

Test | Avg. RAM Usage | Plugin Enabled?
-----|-----|-----
HxD Open (no files) | 6MB | Yes
HxD Open (no files) | 6MB | No
*Opened a 9MB encrypted file | 46MB | Yes
*Opened a 9MB encrypted file | 7MB | No
*Opened a 15MB encrypted file | 680MB | Yes
*Opened a 15MB encrypted file | 7MB | No

*These tests were simply opening the file and watching Task Manager; no scrolling, selecting, or anything was done in HxD. The CPU usage reaches nearly 20% until it reaches the "max" RAM. When closing the file, the RAM usage nearly cuts in half, but still stays high (e.g. the 680MB -> 340MB).

- HxD 2.4.0.0 (x86-64) (no other plugins)
- Windows 10 1909
- i7 9th gen w/ 16GB RAM

Screenshot with the 15MB file open:

![image](https://user-images.githubusercontent.com/5551512/95784639-d3ed3580-0c99-11eb-9a1e-4baf644ae614.png)

Attaching one of the example files that triggers this reliably (zipped, it is an encrypted file).

[8A5B5897.JPG.zip](https://github.com/stong/hxd-plugin/files/5367200/8A5B5897.JPG.zip)

**Comment by stong** [comment]
Ugh, the issue is HxD selects the entire rest of the file if you place your caret and don't make a selection, I will fix this

**Comment by stong** [comment]
I fixed it by doing some evil  unsupported shit

```c
	// ["HxD.exe" + 0052A938] = pointer to globalObj
	// [globalObj + b8] = pointer to curFile
	// [curFile + 8] = pointer to editorStruct
	// [editorStruct + 798] = selection size
	void* globalObj = *(void**)((uintptr_t) hHxD + 0x0052A938);
	if (!globalObj)
	{
		// WTF? This shouldn't happen
		return 0;
	}
	void* curFile = *(void**)((uintptr_t)globalObj + 0xb8);
	if (!curFile)
	{
		// No file open
		return 0;
	}
	void* editorStruct = *(void**)((uintptr_t)curFile + 0x8);
	uint64_t selectionSize = *(uint64_t*)((uintptr_t)editorStruct + 0x798);
	return selectionSize;
```

The performance is still poor if a selection is huge, so I limit it to 0x10000 as well.

**Comment by Demonslay335** [comment]
Confirmed fixed, thanks for the quick turn-around! Very helpful plugin for what I do on a daily basis. 😄
